export class Guest {
    _id: string = ''
    username: string = ''
    password: string = ''
    security_question: string = ''
    security_question_answer: string = ''
    firstname: string = ''
    lastname: string = ''
    gender: string = ''
    address: string = ''
    phone_number: string = ''
    email: string = ''
    credit_card_number: string = ''
    profile_photo: string = ''
    active: string = ''
    late_for_reservation: string = ''
}