export const securityQuestions = [
  { label: "What was the name of your first pet?", value: 1 },
  { label: "What is your mother's maiden name?", value: 2 },
  { label: "What was the make and model of your first car?", value: 3 },
  { label: "In what city were you born?", value: 4 },
  { label: "What high school did you attend?", value: 5 },
  { label: "What is the name of your favorite childhood friend?", value: 6 },
  { label: "What was the name of your elementary school?", value: 7 },
  { label: "What is the name of the first company you worked for?", value: 8 },
  { label: "What is your favorite food?", value: 9 },
  { label: "What is the name of your favorite teacher?", value: 10 },
  { label: "What was the name of your first stuffed animal?", value: 11 },
  { label: "What was your dream job as a child?", value: 12 },
  { label: "What street did you grow up on?", value: 13 },
  { label: "What was the name of your first boyfriend/girlfriend?", value: 14 },
  { label: "What was the name of your first grade teacher?", value: 15 },
  { label: "What is your favorite movie?", value: 16 },
  { label: "What is your father's middle name?", value: 17 },
  { label: "What was the name of your first employer?", value: 18 },
  { label: "Where did you go on your first vacation?", value: 19 },
  { label: "What is the name of your favorite book?", value: 20 }
];
